[workspace]
resolver = "2"
members = [
    "surrealdb_extra",
    "surrealdb_extra_derive",
    "surrealdb_extra_tests",
    "surrealdb_extra_bench",
]

[workspace.dependencies]
surrealdb = { version = "1.1.0" }

[workspace.package]
version = "0.7.1"
edition = "2021"