[package]
name = "surrealdb_extra"
version = "0.6.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Adds a orm and query builder on top of surrealdb"
readme = "crates-io.md"
documentation = "https://docs.rs/surrealdb_extra"
repository = "https://github.com/jakin010/surrealdb_extra"
keywords = ["surrealdb", "surrealdb_extra", "surrealdb_orm", "orm", "query_builder"]
categories = ["database", "database-implementations"]

[dependencies]
surrealdb_extra_derive = { version = "0.6.0", path = "../surrealdb_extra_derive" }
async-trait = "0.1.75"
surrealdb = "1.0.2"
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.51"
anyhow = "1.0.76"
chrono = "0.4.31"

[features]
default = ["derive"]
table = []
query = ["derive"]
derive = ["table"]

[dev-dependencies]
serde_with = "3.4.0"
surrealdb = { version = "1.0.2", features = ["kv-mem"] }
tokio = { version = "1.35.1", features = ["macros"] }

# docs.rs-specific configuration
[package.metadata.docs.rs]
# document all features
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
