[package]
name = "surrealdb_extra"
version = "0.4.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Adds a orm and query builder on top of surrealdb"
readme = "crates-io.md"
documentation = "https://docs.rs/surrealdb_extra"
repository = "https://github.com/jakin010/surrealdb_extra"
keywords = ["surrealdb", "surrealdb_extra", "surrealdb_orm", "orm", "query_builder"]
categories = ["database", "database-implementations"]

[dependencies]
surrealdb_extra_derive = { version = "0.4.0", path = "../surrealdb_extra_derive" }
async-trait = "0.1.68"
surrealdb = "1.0.0"
serde = { version = "1.0.163", features = ["derive"] }
thiserror = "1.0.40"
anyhow = "1.0.75"
chrono = "0.4.29"
itertools = "0.11.0"
rayon = "1.7.0"

[features]
default = ["derive"]
table = []
query = ["derive"]
derive = ["table"]

[dev-dependencies]
surrealdb = { version = "1.0.0", features = ["kv-mem"] }
tokio = { version = "1.28.1", features = ["macros"] }

# docs.rs-specific configuration
[package.metadata.docs.rs]
# document all features
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
