[package]
name = "surrealdb_extra_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
surrealdb = "1.0.0-beta.9"
syn = { version = "2.0.16", features = ["derive"] }

[dev-dependencies]
surrealdb_extra = { path = "../surrealdb_extra" }